server:
  port: ${app.port}
  address: 0.0.0.0
spring:
  application:
    name: memes
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 4
      maximum-pool-size: 20
      pool-name: "appPool"
      auto-commit: true
      connection-timeout: 20000
      allow-pool-suspension: false
    driver-class-name: org.postgresql.Driver
    jdbcUrl: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
service:
  consul:
    kv_src: ${consul.kv_src}
  tree:
    name: ${tree.name}
    read-timeout: ${tree.read_timeout}
    connection-timeout: ${tree.connection_timeout}
  feed:
    page-item-count: ${feed.page_item_count}
  worker:
    delay: ${worker.delay}
  vk:
    app_id: ${vk.app_id}
    client_secret: ${vk.client_secret}
    service_key: ${vk.service_key}
    memes_count: ${vk.memes_count}
    startup_memes_count: ${vk.startup_memes_count}
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
logging.level.com.clhost.memes.app.tree.TreeClient: DEBUG