server:
  port: 8090
  address: 0.0.0.0
spring:
  application:
    name: vp-tree
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 4
      maximum-pool-size: 20
      pool-name: "treePool"
      auto-commit: true
      connection-timeout: 20000
      allow-pool-suspension: false
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/docker #${datasource.url}
    username: docker #${datasource.username}
    password: docker #${datasource.password}
  liquibase:
    change-log: "classpath:sql/schema_changelog.yaml"
service:
  tree:
    count_of_hashes: 1000
    bit_resolution: 512
    duplicate_threshold: 0.2
    bucket_duplicate_threshold: 0.6
    is_normalized_distance: true
  minio:
    endpoint: localhost
    port: 9000
    access_key: "AKIAIOSFODNN7EXAMPLE"
    secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    bucket_name: memes-bucket
    uploader-workers-count: 10
  queue_capacity: 1000
  image_workers_count: 5