server:
  port: ${app.port}
  address: 0.0.0.0
spring:
  application:
    name: vp-tree
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 4
      maximum-pool-size: 20
      pool-name: "treePool"
      auto-commit: true
      connection-timeout: 20000
      allow-pool-suspension: false
    driver-class-name: org.postgresql.Driver
    jdbcUrl: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  liquibase:
    change-log: "classpath:sql/schema_changelog.yaml"
service:
  tree:
    count_of_hashes: ${tree.count_of_hashes}
    bit_resolution: ${tree.bit_resolution}
    duplicate_threshold: ${tree.duplicate_threshold}
    bucket_duplicate_threshold: ${tree.bucket_duplicate_threshold}
    is_normalized_distance: ${tree.is_normalized_distance}
  s3:
    endpoint: ${s3.endpoint}
    port: ${s3.port}
    access_key: ${s3.access_key}"
    secret_key: ${s3.secret_key}
    bucket_name: ${s3.bucket_name}
    upload-workers-count: ${s3.upload_workers_count}
  queue_capacity: ${queue_capacity}
  image_workers_count: ${image_workers_count}
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true